version: 0.2

env:
  variables:
    ENVIRONMENT_NAME: "production"

phases:
  install:
    commands:
      - echo Running install phase
    finally:
      - echo Executing install phase finally
  pre_build:
    commands:
      - echo Running pre_build phase
    finally:
      - echo Executing pre_build phase finally
  build:
    commands:
      - echo Running build phase
      - echo Environment is $(ENVIRONMENT_NAME) 
    finally:
      - echo Executing build phase finally
  post_build:
    commands:
      - echo Running post_build phase
    finally:
      - echo Executing post_build phase
artifacts:
  files:
    - '**/*'