AWSTemplateFormatVersion: '2010-09-09'
Description: This template will build the pipeline needed to deploy an Angular application
Parameters:
  EnvironmentName:
    Type: String
    Default: Production
    Description: The name of the environment that this pipeline is being created for
Resources:
  AngularAppBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - 
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        -
          PolicyName: !Sub
            - TestAngularBuildPolicy-${Environment}
            - { Environment: !Ref EnvironmentName }
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - 
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                Resource: '*'